# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-21 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheapest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('reg_registrar', models.CharField(max_length=30)),
                ('reg_price', models.FloatField()),
                ('renew_registrar', models.CharField(max_length=30)),
                ('renew_price', models.FloatField()),
                ('tran_registrar', models.CharField(max_length=30)),
                ('tran_price', models.FloatField()),
                ('popularity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatetime', models.DateTimeField()),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=30)),
                ('registry', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('cate', models.CharField(max_length=30)),
                ('popular', models.IntegerField()),
                ('restrictions', models.CharField(max_length=200)),
                ('sources', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register', models.FloatField()),
                ('renewal', models.FloatField()),
                ('transfer', models.FloatField()),
                ('whois', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=30)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
