# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-22 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tld', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='domain',
            table='domain',
        ),
        migrations.AlterModelTable(
            name='price',
            table='price',
        ),
        migrations.AlterModelTable(
            name='registrar',
            table='registrar',
        ),
    ]
