# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-22 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tld', '0002_auto_20180222_0955'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='domain',
            table='domains',
        ),
        migrations.AlterModelTable(
            name='price',
            table='prices',
        ),
        migrations.AlterModelTable(
            name='registrar',
            table='registrars',
        ),
    ]
